name: Build and Release
on:
  workflow_dispatch:

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.x"

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.9"

      - name: Generate Version
        id: shell
        run: |
          echo "version=$(date -u '+%Y.%-m%d.%-H%M.0')" >> $GITHUB_OUTPUT

      - name: Build Jellyfin Plugin for release
        run: |
          dotnet build -c Release /p:Version=${{ steps.shell.outputs.version }}

      - name: Print Folder Tree
        uses: jaywcjlove/github-action-folder-tree@main
        with:
          exclude: "obj|.git"
          path: .
          depth: 8

      - name: Generate Manifest
        run: |
          python3 scripts/manifest.py Jellyfin.Plugin.PhoenixAdult@v${{ steps.shell.outputs.version }}.zip

      - name: Publish Manifest
        run: |
          git config --global user.name  'phoenixadult-bot'
          git config --global user.email 'phoenixadult-bot@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/Andrer757/Jellyfin.Plugin.PhoenixAdult.git

          git checkout master
          git add manifest.json
          git commit -m "Auto Updated by Actions"
          git push origin master

      - uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.shell.outputs.version }}
          prerelease: false
          generate_release_notes: true
          files: |
            **/Jellyfin.Plugin.PhoenixAdult@v${{ steps.shell.outputs.version }}.zip